### ISSUE TITLE
Worked fine with Authoring Tool v 0.1.1 but doesn't seem to with 0.1.2 which is a real shame - do you have plans to make this compatible with Framework 2.0.x?

### ISSUE THREAD

**Issue by hbaileylxd** [ExultCorp/adapt-contrib-flipcard#2]

**Comment by hbaileylxd** [comment]
In Chrome debugger I get the following

adapt/js/adapt.min.js:116 Sorry, no resources object is set on the course.json file
adapt/js/adapt.min.js:105 Uncaught TypeError: a is not a function

**Comment by hbaileylxd** [comment]
It works now! A few grunt:builds and voila! Working! Thanks guys!
